name: julio33

on:

        Push:
        workflow_dispatch:

jobs:

  build:

     runs-on: ubuntu-latest

     steps:

         - uses: actions/checkout@v3

         - name: SonarCloud Scan
         - uses: 

test:
   needs: build
   runs-on: ubuntu-latest

steps:

  - name: Hola
    run: | 
       echo "hola"
