# Ac치 va el nombre (Integracion Continua)
name: CI
# Ac치 se declaran los eventos
on:
# Si se ejecuta el push cada vez
 push:
 workflow_dispatch:
# Ac치 es donde se declaran los trabajos y los pasos (jobs --< steps)
jobs:
  
 build:   
  runs-on: ubuntu-latest  
  steps:  
   - uses: actions/checkout@v3   
   - name: Inicio
     run: |
       echo "Jelou Jelou"
#Conexion con SonarCloud 
 SAST_SonarCloud:
  runs-on: ubuntu-latest
  needs: build  
  steps:
  - name: Checkout repository
    uses: actions/checkout@v3
 
  - name: Setup Node.js
    uses: actions/checkout@v3
    with:
      node-version: '14'
 
  - name: Install dependencies
    run: npm install
 
  - name: Run SonarCloud analysis
    uses: sonarsource/sonarcloud-github-action@master
    
    #Tokens de Seguridad
    env:
      GITHUB_TOKEN: ${{ github_token }}
      SONAR_TOKEN: ${{ TOKEN33 }}
#Integracion SCA
 SCA_DependencyCheck:
  runs-on: ubuntu-latest
  needs: build
  steps:
  - name: Dependency Check
    uses: dependency-check/Dependency-Check_Action@1.1.0
    with:    
      project: 'final-lab'
      path: '.'
      format: 'HTML' 
     
  - name: Upload Test results
    uses: actions/upload-artifact@master
    with:
      name: Depcheck report
      path: ${{github.workspace}}/reports

#Integraci칩n con DOCKER
 SecurityTrivy_Docker:   
  runs-on: ubuntu-latest
  needs: [SAST_SonarCloud, SCA_DependencyCheck]

  steps: 
   - name: Checkout code
     uses: actions/checkout@v3

 #Build
   - name: Build Docker image
     run: |
       docker build -t JulioCesar393/final-lab:latest .
       
 #Analisis de imagen
   - name: Run Trivy vulnerability scanner
     uses: aquasecurity/trivy-action@master
     with:
       image-ref: 'JulioCesar393/final-lab:latest'
       format: 'table'
       exit-code: '1'
       ignore-unfixed: true
       vuln-type: 'os,library'
       severity: 'CRITICAL,HIGH,MEDIUM,LOW'


